---
- name: phpApps
  hosts: all
  become: yes
  become_method: sudo  
  vars_files:
    - vars/main.yml

  vars_prompt:
    - name: 'webs_selection'
      prompt: "\nChoose serial number to install Web-Server? [ 1/2 ] \n\n
      1: Apache\n
      2: Nginx\n\n"
      private: no
      default: 1

    - name: 'php_choose'
      prompt: "\nChoose serial number to install PHP [ 1/2/../6 ]\n\n
      1: PHP 5.6\n
      2: PHP 7.0\n
      3: PHP 7.1\n
      4: PHP 7.2\n
      5: PHP 7.3\n
      6: PHP 7.4\n\n"
      private: no
      default: 4

    - name: 'mysql_choose'
      prompt: "\nChoose serial number to install MySQL [ 1/2/../4 ] \n\n
      1: MySQL 5.5(only for CentOS7.x, AmazonLinux)\n
      2: MySQL 5.6\n
      3: MySQL 5.7\n
      4: MySQL 8.0\n\n"
      private: no
      default: 3

    - name: 'phpapps_selection'
      prompt: "\nYou can install or not install one of below applicatons\n\r
      {{phpapps_meta.keys()|list |to_nice_json}}\n\n
      Input application name or press Enter directly for no application"
      private: no

  vars:
    webs_select:
      '1': 'apache'
      '2': 'nginx'
      
    infrastructure_select:
      '1': 'LAMP'
      '2': 'LNMP'

    select_mysql_ver:
      '1': "5.5"
      '2': "5.6"
      '3': "5.7"
      '4': "8.0"

    select_php_ver:
      '1': "5.6"
      '2': "7.0"
      '3': "7.1"
      '4': "7.2"
      '5': "7.3"
      '6': "7.4"

     # Public variables
    phpapps_webs: "{{webs_select[webs_selection]}}"          
    w9panel_webs: "{{webs_select[webs_selection]}}" 
    w9panel_set_infrastructure: "{{infrastructure_select[webs_selection]}}" 

  pre_tasks:
    - block: 
      - set_fact:
      # apps variables
          php_version: "{{phpapps_meta[phpapps_selection].phpver}}" 
          phpapps_name: "{{phpapps_meta[phpapps_selection].name}}"
          phpapps_title: "{{phpapps_meta[phpapps_selection].title}}"      
          phpapps_documentroot: "{{phpapps_meta[phpapps_selection].documentroot}}"
          phpapps_config_paths: "{{phpapps_meta[phpapps_selection].config_paths}}"
          phpapps_commands: "{{phpapps_meta[phpapps_selection].commands}}"
          w9panel_set_apps: 
            - "{{phpapps_meta[phpapps_selection].title}}"

          mysql_version: "{{phpapps_meta[phpapps_selection].mysqlver}}" 
          
      # apps second variables 
      - set_fact:
          mysql_databases:
            - name: "{{phpapps_name}}"

          mysql_users:
            - name: "{{phpapps_name}}"
              priv: '{{phpapps_name}}.*:ALL'

          php_ioncube: "{{ (phpapps_name == 'chanzhi' or phpapps_name == 'zdoo') | ternary(True,False) }}"
          docker_applications_select: "{{ (phpapps_name == 'dzzoffice') | ternary(['phpmyadmin','onlyofficedocs'],['phpmyadmin']) }}"

          init_db:
            mysql:
              admin: root
              users: ["{{phpapps_name}}"]
              password: "123456"
              service_before: "php-fpm.service"
              config_paths: "{{phpapps_config_paths}}"
              commands: "{{phpapps_commands}}"

      - debug: 
          msg: Selected application is {{phpapps_name}}, Web app is {{w9panel_webs}}, PHP version is {{php_version}}, Mysql version is {{mysql_version}}
        
      when: phpapps_selection != ""

    - block: 
      - set_fact:
      # lamp or lnmp  variables
          mysql_version: "{{select_mysql_ver[mysql_choose]}}"
          php_version: "{{select_php_ver[php_choose]}}"
          docker_applications_select: 
            - phpmyadmin

          init_db: 
            mysql:
              admin: root
              password: "123456"

      - debug:
          msg: "{{w9panel_set_infrastructure}} will be installed, PHP version is {{php_version}}, Mysql version is {{mysql_version}}"

      when: phpapps_selection == ""

    - debug:
        msg: 'docker applications is {{item}}'
      with_items: '{{docker_applications}}'
        
  roles:
    - {role: role_common, tags: "role_common"}
    - {role: role_cloud, tags: "role_cloud"}
    - {role: role_apache, tags: "role_apache", when: phpapps_webs == 'apache'}
    - {role: role_nginx, tags: "role_nginx", when: phpapps_webs == 'nginx'}
    - {role: role_mysql, tags: "role_mysql"}
    - {role: role_php, tags: "role_php"}
    - {role: role_inotify_watch, tags: "role_inotify_watch"}
    - {role: role_docker, tags: "role_docker"}
    - {role: role_9panel, tags: "role_9panel"}
    - {role: role_redis, tags: "role_redis"}
    - {role: phpapps, tags: "phpapps", when: phpapps_selection != ""}
    - {role: role_init, tags: "role_init"}
    - {role: role_preend, tags: "role_preend"}
    - {role: role_end, tags: "role_end"}
