---
#引入PHP运行环境元数据，并初始化
- include_vars: roles/role_php/vars/php_runtime_meta.yml

#Modify var for this playbook
- set_fact:
    kodcloud_vhost_dir: "{{php_runtime_meta[ansible_os_family][phpapps_webs].vhost_dir}}"
    kodcloud_vhost_src: "{{php_runtime_meta[ansible_os_family][phpapps_webs].vhost_src}}"
    kodcloud_service: "{{php_runtime_meta[ansible_os_family][phpapps_webs].service}}"
    kodcloud_owner: "{{php_runtime_meta[ansible_os_family][phpapps_webs].owner}}"
    kodcloud_name: "{{phpapps_name}}"
    kodcloud_title: "{{phpapps_title}}"
    kodcloud_download_url: "https://github.com/kalcaddle/kodbox/archive/refs/heads/main.zip"

- debug:
    msg: runtime {{ kodcloud_vhost_dir }}, {{kodcloud_vhost_src}}, {{kodcloud_service}}, {{kodcloud_owner}}, {{ansible_distribution}}


# kodcloud
- name: Remove extra dir
  shell: rm -rf /data/wwwroot/*{{kodcloud_name}}*

- name: Download from {{ kodcloud_download_url }}
  unarchive:
    src: "{{ kodcloud_download_url }}"
    dest: /data/wwwroot
    remote_src: yes
  
- name: Rename dir name
  shell: cd /data/wwwroot; if [ ! -d "{{kodcloud_name}}" ]; then mv kod* {{kodcloud_name}}; fi

- name: Copy Apache or Nginx vhost configuration
  template: src={{kodcloud_vhost_src}} dest={{kodcloud_vhost_dir}}
