---
- debug:
    msg: suitecrm is installing now 

#引入PHP运行环境元数据，并初始化
- include_vars: roles/role_php/vars/php_runtime_meta.yml

#Modify var for this playbook
- set_fact:
    suitecrm_vhost_dir: "{{php_runtime_meta[ansible_os_family][phpapps_webs].vhost_dir}}"
    suitecrm_vhost_src: "{{php_runtime_meta[ansible_os_family][phpapps_webs].vhost_src}}"
    suitecrm_service: "{{php_runtime_meta[ansible_os_family][phpapps_webs].service}}"
    suitecrm_owner: "{{php_runtime_meta[ansible_os_family][phpapps_webs].owner}}"
    suitecrm_name: "{{phpapps_name}}"
    suitecrm_title: "{{phpapps_title}}"
    # 不要使用Github发布的地址，原因是这个Github上的源码还需要通过composer下拉外部依赖包，如果PHP环境没有安装 composer 或 composer 版本不符合要求，就会导致 SuiteCRM 无法安装
    #suitecrm_download_url: "https://suitecrm.com/files/162/SuiteCRM-7.11/525/SuiteCRM-7.11.18.zip"
    suitecrm_download_url: "https://udomain.dl.sourceforge.net/project/suitecrm/SuiteCRM-7.11.19.zip"
                            
- debug:
    msg: runtime {{ suitecrm_vhost_dir }}, {{suitecrm_vhost_src}}, {{suitecrm_service}}, {{suitecrm_owner}}, {{ansible_distribution}}

# suitecrm
- name: Remove extra dir
  shell: rm -rf /data/wwwroot/*{{suitecrm_name}}*
  
- name: create app dir
  shell: mkdir /data/wwwroot/{{suitecrm_name}}
 
- name: Download {{suitecrm_name}} from {{ suitecrm_download_url }}
  unarchive:
    src: "{{ suitecrm_download_url }}"
    dest: /data/wwwroot/{{suitecrm_name}}
    remote_src: yes

- name: Rename dir name
  shell: cd /data/wwwroot; if [ ! -d "{{suitecrm_name}}" ]; then mv *SuiteCRM* {{suitecrm_name}}; fi

- name: create crontab task
  shell: echo "* * * * * cd /data/wwwroot/{{suitecrm_name}}; /usr/bin/php -f cron.php > /dev/null 2>&1" >> /etc/crontab

- name: Copy Apache or Nginx vhost configuration
  template: src={{suitecrm_vhost_src}} dest={{suitecrm_vhost_dir}}

- name: Check suitecrm version
  shell: >
    sudo echo "suitecrm version:" $(cat /data/wwwroot/suitecrm/suitecrm_version.php |grep suitecrm_version |cut -d= -f2) |sudo tee -a /data/logs/install_version.txt  

