---
- debug:
    msg: vtigercrm is installing now 

#引入PHP运行环境元数据，并初始化
- include_vars: roles/role_php/vars/php_runtime_meta.yml

#Modify var for this playbook
- set_fact:
    vtigercrm_vhost_dir: "{{php_runtime_meta[ansible_os_family][phpapps_webs].vhost_dir}}"
    vtigercrm_vhost_src: "{{php_runtime_meta[ansible_os_family][phpapps_webs].vhost_src}}"
    vtigercrm_service: "{{php_runtime_meta[ansible_os_family][phpapps_webs].service}}"
    vtigercrm_owner: "{{php_runtime_meta[ansible_os_family][phpapps_webs].owner}}"
    vtigercrm_name: "{{phpapps_name}}"
    vtigercrm_title: "{{phpapps_title}}"
    vtigercrm_download_url: "https://sourceforge.net/projects/vtigercrm/files/vtiger%20CRM%207.4.0/Core%20Product/vtigercrm7.4.0.tar.gz"
    
- debug:
    msg: runtime {{ vtigercrm_vhost_dir }}, {{vtigercrm_vhost_src}}, {{vtigercrm_service}}, {{vtigercrm_owner}}, }, {{ansible_distribution}}

# vtigercrm
- name: Remove extra dir
  shell: rm -rf /data/wwwroot/*{{vtigercrm_name}}*
  
- name: Download VtigerCRM
  unarchive:
    src: "{{ vtigercrm_download_url }}"
    dest: /data/wwwroot
    remote_src: yes

- name: Rename dir name
  shell: cd /data/wwwroot; if [ ! -d "{{vtigercrm_name}}" ]; then mv *{{vtigercrm_name}}* {{vtigercrm_name}}; fi


- block:
  - name: modify MySQL configuration
    blockinfile:
      path: /etc/my.cnf
      insertafter: "server_id=1"
      block: |
        sql_mode = ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

  - name: modify MySQL collation utf8_general_ci
    shell: mysql -uroot -p123456 -e "ALTER DATABASE vtigercrm CHARACTER SET utf8 COLLATE utf8_general_ci;"

  - name: modify php configuration error_reporting
    lineinfile:
      path: /etc/php.ini
      regexp: 'error_reporting = *'
      line: 'error_reporting = E_WARNING & ~E_NOTICE & ~E_DEPRECATED & ~E_STRICT'

  - name: modify php configuration log_errors
    lineinfile:
      path: /etc/php.ini
      regexp: 'log_errors = On'
      line: 'log_errors = Off'

  - name: modify php configuration short_open_tag 
    lineinfile:
      path: /etc/php.ini
      regexp: 'short_open_tag = On'
      line: 'short_open_tag = Off'

- name: Copy Apache or Nginx vhost configuration
  template: src={{vtigercrm_vhost_src}} dest={{vtigercrm_vhost_dir}}

- name: Check vtigercrm version
  shell: >
    sudo echo $(cat /data/wwwroot/vtigercrm/vtigerversion.php  |grep vtiger_current_version |sed -n 1p) |sudo tee -a /data/logs/install_version.txt  
